name: Weekly analytics

on:
  schedule:
    - cron: 0 12 * * 0
  workflow_dispatch:

jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Moscow"

      - name: Install dependencies
        run: |
          python -m pip install google-api-python-client
          python -m pip install oauth2client

      - name: Write secrets
        run: |
          echo '${{ secrets.ANALYTICS_FILE }}' > file.json
          echo '${{ secrets.TEL_USERS_LIST }}' > users.txt

      - name: Making request
        run: python ./.github/workflows/form_analytics.py ${{ secrets.ANALYTICS_VIEW_ID }}

      - name: Notification
        run: |
          cat users.txt | xargs -I {} sh -c '{ \
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"chat_id\": \"{}\", \"text\": \"$(cat message.txt)\", \"parse_mode\": \"HTML\"}" \
              https://api.telegram.org/bot${{ secrets.TOKEN }}/sendMessage; \
            sleep 0.035; \
          }'
